### ISSUE TITLE
OLD PWD not good

### ISSUE THREAD

**Issue by maxdegers** [maxdegers/Minishell#9]
minishell🐚 pwd
/home/mbrousse/Documents/github/Minishell
minishell🐚 env | grep PWD
PWD=/home/mbrousse/Documents/github/Minishell
OLDPWD=/home/mbrousse/Documents/github/Minishell
minishell🐚 cd ..
minishell🐚 env | grep PWD
PWD=/home/mbrousse/Documents/github
OLDPWD=..
minishell🐚

**Comment by MPIT0T** [comment]
All good no leaks
